spicetify/spicetify-themes

Nord/README.md
Nord/color.ini
Nord/user.css

Based on the excellent [nord](https://github.com/arcticicestudio/nord) color scheme.

Add Nord theme

---

Spicy/README.md

That was a typo.

---

Black/README.md
Black/user.css

i added the links in the readme back in the time where i had my own repo. Now the links should work on your repo. I also removed the forced google sans font that would otherwise end up looking ugly because it isnt pre-installed and not many people have it installed.

updated some things on my theme

---

CherryBlossom/README.md
Coral/README.md

Fixed broken hyperlinks in README.md files

Fixed broken hyperlinks in README.md files

---

Dribbblish/README.md
Dribbblish/color.ini
Dribbblish/user.css

`active_control_fg` codes the color of the shuffle and repeat button once activated.

Added yet another Dribbblish option

---

Onepunch/README.md
Onepunch/changelog.md

> I am not going to work on this anymore. If anyone wants to continue it or remake it, feel free to do it. Thank you.
I have updated the readme with the above-quoted message. I am discontinuing this theme. This pull request is just a heads up for that.
Thanks.

Theme discontinued

---

DribbblishDynamic/dribbblish-dynamic.js

FIX for local files #189

---

Dribbblish/user.css

Fix improper centering of player controls

---

NoSleep/README.md

Will link the website in our discussion on Spectrum

Update README.md to include hits tracker

---

README.md

Dribblish is written with 3 Bs, not 2

Fixed spelling mistake on line 18

---

DribbblishDynamic/user.css

Remove 1px padding from tracklist container

---

Gruvbox-Gold/README.md

Hi, I noticed a small typo and corrected it.

Typo fixed

---

DribbblishDynamic/dribbblish-dynamic.js
DribbblishDynamic/user.css

Reverts morpheusthewhite/spicetify-themes#261
I will push a clean fix

Revert "Add Sidebar Color Updates"

---

DribbblishDynamic/user.css

indentation
shamelessly copied from https://github.com/morpheusthewhite/spicetify-themes/commit/4cea2498cd00d07571e053afe96fe88f20e76a10

fix macos sidebar position

---

DribbblishDynamic/dribbblish-dynamic.js

Also fix the brightness threshold for light/dark color switching.

dribblish-dynamic.js: reduce redundancy

---

Midnight-Light/user.css

Remove gradients on Header and Radio tabs

---

Midnight-Light/user.css

Solves https://github.com/morpheusthewhite/spicetify-themes/issues/228

Ensure padlock shows in private session

---

Material-Ocean/user.css

- fix text in card alignment
- fix text being too close to the header in local files
- fix first row being cutoff in artist albums
- fix explicit text colour being the same as the background
- fix clear recent search button hidden under controls when there are a lot of recent searches

Material ocean: more general fixes

---

OldSchoolSenn/color.ini

This makes it a bit more readable on the black background.

Make blue a bit brighter in theme OldSchoolSenn (mine)

---

DribbblishDynamic/dribbblish-dynamic.js
DribbblishDynamic/user.css

Folders look like this: https://imgur.com/a/qUinxRt

Added styling for playlist folders to Dribbblish Dynamic

---

Dribbblish/color.ini

Fixes Toast Notification BG issues and changes "Offline" banner BG color to reflect it being an error.

Fixes Dribbblish/Dracula theme

---

Material-Ocean/user.css

Signed-off-by: blacksuan19 <i@blacksuan19.me>

material ocean: fix lyrics background color

---

Tidal/README.md
Tidal/color.ini
Tidal/user.css

Here's my theme based off of Tidal. I thought I'd add, I started a Discord server for Spicetify https://discord.gg/AmUdJYyGvt. Feel free to join.

Add Tidal theme

---

Dribbblish/user.css
DribbblishDynamic/user.css

Currently the padding is missing and it looks weird
**Before**
**After**

dribbblish: add x padding to "Recommended Songs" header

---

README.md

@morpheusthewhite
I modified some content based on the last time (#381), and match your format in the README.md.
Is there anything that need to be changes or adds?
Thanks for invited me to collaborate this repository! And sorry to created the PR too late, because i am busy recently.

docs(README): add **Commit Message** for standardization commit messages

---

THEMES.md
Ziro/LICENSE
Ziro/README.md
Ziro/color.ini
Ziro/user.css

Ziro changes the progress bar, overhauls the artist page, rounds everything, colors tracklist, adds support for a light accent color, removes shadows and many more tweaks.

Add Ziro theme

---

Ziro/color.ini
Ziro/user.css

patch for spicetify v2.4, fixed dialogs, home & sidebar config buttons, proxy settings

Ziro Fixes

---

Sleek/user.css

Minor fix to match the color of the playing-icon-animation to the rest of the theme.

fix(Sleek): match playing icon to text color

---

THEMES.md
Ziro/README.md

changed locations of my screenshots, so the links were broken

Update screenshot links

---

Onepunch/README.md
Onepunch/color.ini
Onepunch/user.css
Turntable/user.css

* toggle switches.
* now playing bar.
* queue and recent history position

fix(Onepunch): visibility and position of ui element

---

Onepunch/user.css

Shows current playlist in the theme color, as well as hovering over it.

feat(Onepunch): show current playlist in theme color

---

Sleek/user.css

Hi all!
I've made some general improvements to the sleek theme. I made these only for me at first, but decided to pr them as they seem like things that should be added to the theme in general. I'm probably not going to be around to change stuff from what I did here, but feel free to pr changes if there's any mistakes/problems with my code (there probably are lol).
**What I've done:**
- I formatted all the css with prettier to make stuff more consistent, readable, and efficient
- I added transitions in a lot of places where they were missing, like song lists, buttons, progress/volume bars, and much more!
- I know there was already confirmation dialog fixes, but I made it look even better
- I added the song duration back to the progress bar to float above the progress bar on hover (with …

Feat(Sleek): Styling improvements + fixes

---

Sleek/user.css

fix(Sleek): connect bar fix

---

Dreary/color.ini
Dreary/user.css

Fixed the sidebar which was affected heavily due to Spotify Updates

Fix for new version

---

Fluent/README.md
Fluent/fluent.js
Fluent/user.css

- Fix playlist icons not showed after expanding folders (thanks @Salaron)
- Add scrollbar for playlists, also adjust container height (thanks
@Salaron)
- Fix missing playlist pictures (thanks @TheHenkka)
- Update changed class names for some elements
- Fix bugs with new spotify version

Fix Fluent bugs with new spotify update

---

Ziro/user.css

fixes for new lyrics, #541, #542 and more

fix(Ziro): lyrics, fixes

---

manifest.json

Remove schemes option from turntable

---

Sleek/user.css

Remove vector (circle) from input bar to allow padding to be reduced

Correct class to remove vector (circle)

---

Turntable/README.md

As of right now, the directory regarding spicetify has path .config/spicetify and the filename for rotateTurntable.js has the name turntable.js

Change in the name of file and directory

---

Fluent/user.css

Reverts morpheusthewhite/spicetify-themes#652

Revert "Fix icons"

---

Fluent/fluent.js
Fluent/user.css

Added animation to the thumb to better resemble the WinUI slider.
Below is a comparison of WinUI slider (bottom) and the css one (top).

[Fluent] Add slider thumb animation

---

.github/ISSUE_TEMPLATE/bug_report.md

spicetify enable-devtools is not command in spicetify-cli 
correct command is spicetify enable-devtool so i changed it

Update bug_report.md {Typo}

---

Fluent/user.css

Just some ui fixes for the library section
> I don't know much about this, please forgive me
before
after

Fix[Fluent] fix some UI glitches

---

Sleek/user.css

Fixes the search bar icon by making the stroke width 1 (see https://imgur.com/a/N8qyIg2 for bug and fix).
Also, moved the search icon to the right for readability.

fix(Sleek): Fixes search bar icon

---

manifest.json

fix: Remove Fluent from manifest

---

THEMES.md

Move Sleek/Dracula screenshot upwards to its correct place in the layout

docs(THEMES): reposition Sleek/Dracula preview

---

.github/workflows/auto-assign.yml

@williamckha initially I had Fluent here, but I'll remove it in another PR.
There are a lot of themes that I do not know the owners yet however. If anyone could help here that would be awesome!

feat: add auto-assign to themes issues and PRs

---

Ziro/user.css

fix(Ziro): folders

---

Bloom/README.md

docs(Bloom): update README.md
fix- wrong powershell and bash commands on README.md
add- special thanks
fix- wrong shell command for applying theme 
change- clarified issues which may occur and the solution

docs(Bloom): update README.md

---

Bloom/user.css

fix - scrolling issue
fix - alignments

fix(Bloom): scrolling issue

---

Dribbblish/dribbblish.js
Dribbblish/user.css

Playlist images now works again!

fix(Dribbblish): functional playlist image

---

Dribbblish/user.css

fix(Dribbblish): prioritize `rootlist` padding

---

manifest.json

I deleted the other one because i'm no longer maintaining dreary

chore(Dreary): Marketplace support

---

Ziro/user.css

Update theme according to new changes

fix(Ziro): new CSS map updates

---

Ziro/user.css

fix(Ziro): update class names

---

Turntable/user.css

fix(Turntable): album image sticking out

---

Dribbblish/user.css

fix(Dribbblish): main view shrinking

---

Dribbblish/user.css

fix(Dribbblish): main view clipping

---

Dribbblish/user.css

the bs you get every new spotify updates

fix(Dribbblish): user profile button stretching

---

.github/ISSUE_TEMPLATE/bug_report.md

chore: update `Bug Report`

---

BurntSienna/user.css

apparently everybody has been using Times New Roman as a fallback until now 💀

fix(BurntSienna): import fonts

---

README.md

Updated broken themes link to latest one

Update README.md (Broken themes link)

---

README.md

This reduces download times extensively.

Add "--depth=1" for faster cloning

---

Ziro/color.ini

Tokyo Night Theme for Spotify

---

Ziro/user.css

The lyric coloring was completely broken and the theme didn't apply at all anymore.

fix(ziro): lyrics colors

---

Ziro/user.css

fix(ziro): active button text now visible in user's collection (#908)

---

Dribbblish/theme.js
Dribbblish/user.css

fix(Dribbblish): resizing buddyfeed

---

Matte/user.css

fix(Matte): show friend feed and liked songs

---

Ziro/user.css

fix(ziro):show playing status on liked songs

---

Dribbblish/user.css

fix(Dribbblish): grid layout template rename

---

.github/workflows/auto-assign.yml

Don't know if they need to be an org member or something?

chore: update auto-assign.yml

---

Ziro/user.css

fixes #742, fixes #743, fixes #930, fixes schnensch0/ziro#14, fixes schnensch0/ziro#17

fix(Ziro): ylx colors, light theme, playback time

---

Matte/README.md
Matte/color.ini
Matte/user.css

- update color descriptions
- remove transparent window controls by default
- match your episodes icon
- use player height variable
- update readme to follow format
- make topbar in various pages draggable

fix(Matte): small fixes

---

Dribbblish/color.ini
Dribbblish/user.css

hopefully fixes that sidebar bug everyone seems to have #955

fix(Dribbblish): functionality on older vers

---

Blossom/color.ini
Blossom/user.css

fix for issue #951 and general improvements for ylx

fix(Blossom): add ylx compatibility

---

Blossom/user.css

fix(Blossom): rid of playback bar overflow

---

Matte/user.css

fix broken layout in the new update

fix(Matte): override grid-area property

---

text/user.css

- remove 1px top bar gap
- decrease full screen cover art size
- remove artist modal header clipping
- replace back and pause/play button selector
fixes #977

fix(text): make various fixes

---

Dribbblish/theme.js

in favor of https://github.com/SunsetTechuila/imaged-folders which does the job better

chore(dribbblish): remove custom folder icons feature for ylx

---

text/user.css

https://github.com/spicetify/spicetify-cli/pull/2606

fix(text): lyrics text size

---

Turntable/user.css

fix(Turntable): cover art roundness and rotation

---

text/user.css

fix(text): resolve visual issues

---

text/user.css

fix(text): lyrics on the right sidebar visibility

---

Dribbblish/README.md

Fix Samurai filename on readme

Fix Samurai file on Readme

---

Sleek/user.css

Fixed error in a67ee93 so that it does not make the Play Button in the Action Bar appear weird.
Also made the size of the play svg bigger so that it looks better.
Before:
After:

fix(Sleek): small play button in action bar

---

Ziro/user.css

fix(ziro): resolve visual issues with latest marketplace version

---

Ziro/user.css

fix(ziro): make all modal elements visible

---

Sleek/user.css

Before: ![Spotify_CVtkvYxcMi](https://github.com/spicetify/spicetify-themes/assets/49074962/04862aad-9e40-4b50-bea9-2a6693709ed1)
After: ![Spotify_10TFF4bleh](https://github.com/spicetify/spicetify-themes/assets/49074962/b1852bc2-2b16-44a7-91ac-c97514a4bb4b)

fix(THEMES): fix Sleek theme progress bar

---

Dribbblish/user.css

fix(Dribbblish): Fix scrollbar popup

---

Dribbblish/user.css

fix(Dribbblish): play icon on song cards

---

Dribbblish/user.css

- Fixes an issue where the playlist sidebar scrollbar is disabled
https://github.com/spicetify/spicetify-themes/assets/91320047/1e248b22-b512-4228-94ee-e0d1ab370875

fix(Dribbblish): sideBar scrollbar fix

---

Sleek/user.css

fix(sleek): fix toggle size

---

Blossom/user.css
Onepunch/user.css

fix(blossom & onepunch): fix layoutresizer

---

Dribbblish/user.css

Continue fix: #1037
Some button hover effects were still not applied properly. This fixes those.

fix(Dribbblish): hover play buttons

---

Dribbblish/user.css
StarryNight/theme.js
StarryNight/user.css

Fixed grid layout in global nav and make it usable 
Preview:
This PR includes a fix for Starry Night that was unintentionally added. Since it's a small change and related to the other fixes, I'm keeping it here for now to streamline the process. In the future, I'll be more mindful of keeping unrelated changes on separate branches. Apologies for any confusion!

[Dribbblish] Fix grid layout in global nav [StarryNight] Fix Root container glitch #1098

---

text/user.css

- add border transitions
- align now playing text
- restore missing shuffle button

fix(text): make a few style changes

---

Flow/user.css

This commit adds the global nav grid areas to make the theme usable in global nav

fix(Flow): add global nav grid areas

---

text/user.css

fix(text): support global nav, make minor fixes

---

Dribbblish/theme.js
Dribbblish/user.css

Fixes: #1149
PR based on comment in: https://github.com/spicetify/spicetify-themes/pull/1148#issuecomment-2676894031

fix(Dribbblish): dynamically resize topbar width based on left sidebar

---

StarryNight/user.css

Fixing the playlist sidebar being black instead of transparent.

Fix(StarryNight): Playlist sidebar fix

---

text/README.md
text/user.css

desc in respective commits
close #1127, close #1151, close #1163, close #1170, close #1175, close #1176, close #1182

fix(text): general changes

---

text/user.css

-fix artist header
-recolor top bars
-fix search bar styling
-fix tab bar styling
-fix primary button sizing
-fix shuffle button icon
-fix missing custom app icons
close #1201 close #1186

fix(text): improve spotify 1.2.45 compat
