README.md

Since this is different from operating system to operating system it's worth calling out here. I spent a few minutes scratching my head trying to figure out why I was getting theme not found errors. I assumed the Themes directory was the same on MacOS as it is on Linux.

added info about `Themes` folder location

---

README.md

When I first viewed the README for this repo, I completely missed the preview of all themes on the wiki. I figured it might help to make the size of the line in the README that directs readers to the wiki to preview the themes a bit larger, which is what I did.

Make theme link to wiki larger

---

Dribbblish/README.md

The white color scheme is named "light" in one place and "gow" in another, and I had to open `color.ini` to find out the real color scheme name. This fixes it and will make for a better first-time experience.

Dribblish: README: Fix white color scheme references

---

Kaapi/color.ini

Hi @Jom97 , I took your work as a basis for applying the Gruvbox colour palette :
https://github.com/morhetz/gruvbox-contrib
But I couldn't find where the color of "preserve_1" is applied.

add Gruvbox color for Kaapi theme

---

Dribbblish/dribbblish.js

This will add an icon for the custom app JQBX https://github.com/Kasama/spicetify-jqbx
With this pull request https://github.com/Kasama/spicetify-jqbx/pull/1 it should work.
It won't work yet, but after the above is committed, it should.

Add an icon for JQBX

---

Dribbblish/README.md

Add correction on "unistall" -> "uninstall"

docs: rectify typo on uninstall

---

Gruvbox-Gold/color.ini

This (hopefully) removes every last piece of default Spotify green from the Gruvbox-Gold on buttons and progress bars.

Improve Gruvbox-Gold

---

DribbblishDynamic/dribbblish-dynamic.js

It is already like that for Spotify (non local) files @JulienMaille

[Dribbblish Dynamic] Separate artist and album for local files

---

DribbblishDynamic/dribbblish-dynamic.js

This simple modification to the update js adds the ability for the icons in the left menu to update to a dark color when there is a bright background.
This fixes Issue #260
before: see issue.
after (on darker background):
after (on bright background):

Add Sidebar Color Updates

---

DribbblishDynamic/dribbblish-dynamic.js
DribbblishDynamic/user.css

The album cover is now no longer displayed over the friends list and is now inserted in the bar so that the friends list slides up. 
This makes it possible to scroll all the way down in the friends list even when displaying the large cover. 
An example can be seen below.

[DribblishDynamic] Better display of the large album cover in the friends list

---

Onepunch/user.css

The original author of the theme specified a local server for the Spotify logo asset file, which logically caused the logo not to be displayed. I have linked to a public Imgur upload so you can see the logo again.

[Onepunch] Theme is trying to load the Spotify logo from a local server

---

Arc-Dark/color.ini

The BG color used is used as a primary component of the theme, as to ensure it "fits the theme" so to speak

[#312] Updated color.ini so messages are visible

---

Dribbblish/color.ini

Not sure how I missed this, but this fixes the active button indicator colors.

Fixes Dribbblish/Dracula active button indicators

---

Dribbblish/user.css
DribbblishDynamic/user.css

Adds property `border-top-right-radius` to `#view-now-playing.expanded`, since it looked really weird without a border radius while everything else had rounded corners.
Before: 
After:

dribbblish: add border radius to `#view-now-playing`

---

Dribbblish/user.css
DribbblishDynamic/user.css

I just realized that when I made #353, I was using a **really** old version of dribbblish (at least 7 months behind), and the cover image was still on the left. Since 7d174f3b2bcd81c9453d3678b6f2a338ba2049d2 moved it to the right, the single rounded border looks really weird.
This just adds a border radius all around the cover, or if you think that doesn't look good, you can just get rid of the border radius completely.
Before:
After:

dribbblish: fix border radius for "new" cover position

---

Dribbblish/install.ps1

The Windows install script was trying to get the file from the `v2` branch and was trying to get into that path once extracted.
This has been fixed by changing calls for `v2` back to `master`.

fix(Dribblish): fix Windows install script

---

README.md

The contents of the theme folders weren't getting moved to the spicetify themes folder, so setting a theme wouldn't work. Adding the recurse flag copies all the contents

Add recurse flag to Copy-Item in powershell install command

---

Fluent/user.css

Made a minor change to prevent the progress tooltip from pushing elements in the playback controls from getting close to the top of the playback bar. See comments for more info!

[Fluent] Minor change to fix Fluent bug

---

README.md

Update the notes section in README.md for Fluent theme installation. The theme requires installation commands given in it's [readme](https://github.com/morpheusthewhite/spicetify-themes/tree/master/Fluent#readme)

docs(README): update README.md for Fluent theme

---

Sleek/user.css

Modification of user.css in sleek. I think it looks nicer with the padding of the input box being reduced, (text is closer to the left of the input box now), [change on line 275]. However, there is a vector in the input box which has to be removed so that the letters typed by the user aren't covered by it, [change on lines 265-269].
Screenshot of results after changes.

input-bar-modification

---

manifest.json

Add authors fields to manifest so that Spicetify Marketplace can display the original theme authors and not just morpheusthewhite for everything.

Add authors to manifest

---

Turntable/README.md

The 2nd and 3rd ones weren't loading because the filenames changed.

Fix screenshot paths in Turntable readme

---

BurntSienna/user.css

In the BurntSienna theme, the elapsed time wouldn't apply the CSS that was applied to the remaining time. It's possible that Spotify changed the class name. This PR fixes this by adapting the class name in the user.css file.

[BurntSienna] Fixed CSS not applying to elapsed time

---

BurntSienna/user.css

- Changed playlist play button's hover color to orange
- Added horizontal margins to volume bar
- Unified font family and size in menu accessed by clicking account name
- Removed empty space above playlist title and cover on narrow viewports

fix(BurntSienna): Some visual fixes

---

Dribbblish/user.css

adding more padding on top so 3 dot and close and minimize buttons will not any longer seems buggy

fix(Dribbblish): adding more padding on top

---

Dribbblish/user.css

fix(dribbblish): fix sidebar playlist padding

---

Dribbblish/dribbblish.js
Dribbblish/user.css

Edited the grid layout a little bit, to fix two different UI bugs:
- When the friend activity panel is showing, the bottom playback bar is way too long:
after the fix:
- Second bug has to do with the shadow around the main element, as sometimes it is incorrectly drawn and it extends all the way to the bottom:
after the fix:
I removed the `--main-view-height` CSS variable as it's not really useful, considering it doesn't actually reflect the computed height since there is some overlap between it and the bottom bar. The element that actually renders the drop shadow is now on the CSS grid with the other elements so its size is automatically calculated. Other than that, I don't think any of the other changes are particularly invasive.

fix(dribbblish): bottom bar and box shadow

---

Sleek/user.css

Commit bf288f8 changed the sidebar icons from
to
for no reason, this PR reverts the change

fix(Sleek): revert sidebar icons

---

Sleek/user.css

fixes an issue (possibly caused by #883) where liked songs text active color didn't match right, causing it to look like this:
this pr fixes the issue

fix(Sleek): liked songs text + playing icon active state

---

Ziro/user.css

Hi!
This PR fixes a bug which causes the volume bar to be misaligned when spotify connect is active. 
closes #749

fix(ziro): volume bar alignment with spotify connect

---

Ziro/user.css

Currently the "playing" icon is invisible when you don't have the playing playlist select. This PR changes that icon to the same color of the icon which indicates that a playlist is downloaded. 
Before:
After:

fix(ziro): always display playing icon

---

Ziro/user.css

fix(ziro): center playlist downloaded icon

---

Ziro/user.css

Seems like the latest version changed some classes and the volume bar broke again.

fix(ziro): volume bar alignment with spotify connect (again)

---

Turntable/theme.js

Disc not turning, nor next and previous songs showing at bottom:
After fix it is working as inteded: ![Screenshot_20230502_164558](https://user-images.githubusercontent.com/26069774/235701533-d5e9b69a-c009-41ca-9f01-a762033ccb10.png)
One fix was concerning Spicetify buttons, which don't necessarily have a title when creating them with `Spicetify.Topbar.Button`, but rather can use Tippy. Thus, fadBtn must also be looked for by the contents of Tippy.
Another fix made sure that the action performed when clicking fadBtn had effect after the "Full App Display" was loaded.

fix(Turntable): Disc not turning and not showing next and previous songs

---

Ziro/user.css

Fix for issue #933 .
Before:
After:

fix(Ziro): volume slider misalign on spotify connect

---

Blossom/user.css

resolves #928 
preview of transition on hover

fix(Blossom): make time visible

---

text/README.md
text/user.css

fix(text): user settings, consistency

---

Sleek/color.ini

Updated color.ini to change nav-active-text colour to the highlight colour for the wealthy colour scheme
Before:
After:
P.S. had to redo the commits and PR's as I didn't follow the guidelines; I think I have now. New to this, sorry.

fix(sleek): Fixed wealthy colour scheme for the Sleek theme

---

Sleek/color.ini
Sleek/user.css

fixes #988 
- fix nav active background
- recolor tracklist/playlist placeholders
- make playback time background more transparent
- recolor like button on click
- fix nav-active-text in Wealthy color scheme

fix(Sleek): recolor nav active, placeholder, etc.

---

BurntSienna/user.css

Fixed background color on indicator when Spotify is being played from another device.
Before
After

fix(BurntSienna): fix encore accent background color

---

manifest.json
text/user.css

just to denote the two outdated themes, stopping people from installing them and possibly encountering issues.

feat(manifest): add basic version tags

---

Sleek/user.css

In most color schemes, the toggle bars were filled with the same colour and there was no distinction between the indicator and the wrapper background. This commit fixes that.
Before:
After:

fix(Sleek): improve toggle bar

---

Sleek/user.css

The Play Button in the homegrid and main cards were oversized and were enlarging beyond the border on hover. This fixes that.

fix(Sleek): play button clipping

---

.github/workflows/auto-assign.yml

Our current action is always failing, so replacing with our own should improve these matters.
> glaze
Okay, it is now fully working I believe 👌

feat: custom assigning workflow

---

Dribbblish/README.md

updates change color schemes section to add the two gruvbox themes that for some reason wasn't there

chore(Dribbblish): update change color schemes section with gruvbox

---

StarryNight/README.md
StarryNight/theme.js

Messed up applying width from localstorage which makes playbar disappear on startup if the Now Playing View or Queue card isn't already active.

fix(StarryNight): fix zero playbar width on startup and add instruction to resize width

---

text/README.md

40px does not cover the entire button with the new spotify design.
The buttons now cover 64px in height.
The issue can be seen in SC of https://github.com/spicetify/spicetify-themes/issues/1047 and https://github.com/spicetify/spicetify-themes/issues/1057 even if the issues are not regarding that issue.

docs(text): fix and add info regarding transparent window controls

---

Dribbblish/color.ini

Dribbblish: Gruvbox sidebar color fix

---

text/README.md
text/user.css

fixes #1075, fixes #1057, fixes #1080
fix #1069 with https://github.com/spicetify/cli/pull/3079
#1047 support for older spotify versions is low priority, for me

fix(text): support 1.2.40, add ascii headers

---

StarryNight/user.css

fixes Root_container styles in global nav
issue caused by global nav
expected behavior:

fix(StarryNight):  fix main container in global nav

---

text/user.css

See issue: #1092 
Screenshot of carousel:

fix(text): fix overflow in Liked Songs genre carousel

---

Dribbblish/user.css

Navbar after maybe the new update sticks to the topbar and looks ugly.
This is becase it's being injected negative value from:
```css
.Root__globalNav {
...
margin: calc(var(--panel-gap)*-1);
padding: calc(var(--panel-gap));
position: relative;
}
```
This PR resets the margin to default value and makes the navbar look more seemless.

Fix Dribbblish narbar offset

---

Dribbblish/user.css

Recently, Spotify introduced an update that integrates the search history list into the search bar.
i have resolved the issue where the search history list was being hidden due to this update.

fix(Dribbblish): search history list being hidden

---

text/README.md

Modify height attribute and add margin-top attribute to align with new Spotify client button positions
Before:
After:

chore(text): update snippet

---

text/user.css

Fix for #1151 and #1131.
The CSS was being fixed, but I'm not sure what the exact fix was for that line. Please review it, @darkthemer.

fix(Text): home carrousel width

---

text/user.css

when the keyboard had focus on the category selector the border-radius wouldn't apply this fixes this 
before:
after:

fix(text): corrected border-radius on active tab in category selector

---

Dribbblish/color.ini

based of https://github.com/rebelot/kanagawa.nvim

feat(Dribbblish): add `kanagawa` color scheme
